[package]
name = "daos-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psf-rs = "=2.0.2"
x86_64 = "=0.14.12"
